name: Theme Preview Workflow

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
    paths:
      - "themes/index.js"
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  themePreview:
    name: Theme Preview Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # for script testing checkout the branch
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install & Theme Preview
        run: |
          pnpm install
          pnpm run generate:theme-preview
        env:
          CI: true
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
