name: Theme preview generator

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - "themes/index.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, preview theme
        run: |
          npm install
          npm run gen-theme-preview
        env:
          CI: true
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
